name: Terraform Diff Analysis

# Allow manual triggering of the workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  terraform-diff:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Adjust version as needed
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download Go dependencies
      run: go mod tidy    
    - name: Run Terraform Diff Analysis
      run: |
        echo "🚀 Starting Terraform diff analysis..."
        echo "=============================================="
        
        echo "Comparing:"
        echo "  Old: test-terraform-repo v1.0.0"
        echo "  New: test-terraform-repo v1.1.0"
        echo ""
        
        # Run the Go program with the specified paths
        go run main.go jahnavibavuluri test-terraform-repo v1.0.0 v1.1.0
        
    - name: Summary
      if: always()
      run: |
        echo ""
        echo "=============================================="
        echo "✅ Terraform diff analysis completed!"
        echo "Check the output above for detailed changes."