name: Terraform Diff Analysis

# Allow manual triggering of the workflow
on:
  workflow_dispatch:
    inputs:
      old_version_path:
        description: 'Path to old version directory (e.g., ./test-a/mock-v1.0/)'
        required: false
        default: './test-a/mock-v1.0/'
      new_version_path:
        description: 'Path to new version directory (e.g., ./test-a/mock-v2.0/)'
        required: false
        default: './test-a/mock-v2.0/'
  push:
    branches:
      - main
    paths:
      - 'test-a/mock-v1.0/**'
      - 'test-a/mock-v2.0/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  terraform-diff:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Adjust version as needed
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download Go dependencies
      run: go mod tidy
      
    - name: Verify test directories exist
      run: |
        echo "Checking if directories exist..."
        OLD_PATH="${{ github.event.inputs.old_version_path || './test-a/mock-v1.0/' }}"
        NEW_PATH="${{ github.event.inputs.new_version_path || './test-a/mock-v2.0/' }}"
        
        if [ ! -d "$OLD_PATH" ]; then
          echo "❌ Old version directory not found: $OLD_PATH"
          exit 1
        fi
        
        if [ ! -d "$NEW_PATH" ]; then
          echo "❌ New version directory not found: $NEW_PATH"
          exit 1
        fi
        
        echo "✅ Both directories found"
        echo "Old version path: $OLD_PATH"
        echo "New version path: $NEW_PATH"
        
        # List contents of directories
        echo ""
        echo "Contents of $OLD_PATH:"
        ls -la "$OLD_PATH" || echo "Could not list contents"
        
        echo ""
        echo "Contents of $NEW_PATH:"
        ls -la "$NEW_PATH" || echo "Could not list contents"
        
    - name: Run Terraform Diff Analysis
      run: |
        echo "🚀 Starting Terraform diff analysis..."
        echo "=============================================="
        
        OLD_PATH="${{ github.event.inputs.old_version_path || './test-a/mock-v1.0/' }}"
        NEW_PATH="${{ github.event.inputs.new_version_path || './test-a/mock-v2.0/' }}"
        
        echo "Comparing:"
        echo "  Old: $OLD_PATH"
        echo "  New: $NEW_PATH"
        echo ""
        
        # Run the Go program with the specified paths
        go run main.go "$OLD_PATH" "$NEW_PATH"
        
    - name: Summary
      if: always()
      run: |
        echo ""
        echo "=============================================="
        echo "✅ Terraform diff analysis completed!"
        echo "Check the output above for detailed changes."